/**
 * cloudempiere
 * Cloudempiere API allow programatically access general data
 *
 * OpenAPI spec version: 2018-04-18T10:51:18Z
 * Contact: info@cloudempiere.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

'use strict';
import { MatReceiptPOSTRequestMInoutLine } from './MatReceiptPOSTRequestMInoutLine';

export interface MatReceiptPOSTRequest {
	AD_Org_ID?: number;

	SalesRep_ID?: number;

	C_DocType_ID?: number;

	DocumentNo?: string;

	MovementDate?: string;

	C_BPartner_ID?: number;

	C_BPartner_Location_ID?: number;

	M_Warehouse_ID?: number;

	AD_User_ID?: number;

	POReference?: string;

	M_InoutLine?: Array<MatReceiptPOSTRequestMInoutLine>;
}
